### ISSUE TITLE
Scroll in the terminal window

### ISSUE THREAD

**Issue by Lenrockus** [zeevy/grblcontroller#107] opened 2019-05-21 17:56 UTC
It seems that scroll , doesn't work in the terminal window. V1.25 grbl controller+ neither v1.24

**Comment by zeevy** [comment] 2019-05-22 01:13
Thank you for reporting,
I will check, can you tell me which version of android your are using

**Comment by Lenrockus** [comment] 2019-05-22 04:40
5.02 and 7.0

**Comment by Lenrockus** [comment] 2019-05-24 06:47
same problem v1.26

**Comment by zeevy** [comment] 2019-05-24 06:49
I am unable to reproduce this problem.
Tested in Android 4.4, 6, 8.1, 9
I don't have device with 7.0 or 5.02. 
I do have android 5.1 phone, i will check with that

**Comment by zeevy** [comment] 2019-05-24 06:50
Does the scroll working for you in free version?

**Comment by Lenrockus** [comment] 2019-05-24 08:43
Yes, it works in free version. It also works on paid version 1.23

**Comment by Lenrockus** [comment] 2019-05-24 09:09
[https://youtu.be/bHV9P1n6624](url)
here is video of how it looks like

**Comment by zeevy** [comment] 2019-05-24 13:40
Yes that looks like an issue with small screen mobiles.
Thanks for the video. I think I know where to fix it. 

Can you try by decreasing the display size if supported by your phone.

**Comment by Lenrockus** [comment] 2019-05-25 15:43
Unfortunately my phones doesn't support display resizing.

**Comment by Lenrockus** [comment] 2019-05-25 19:11
Sorry, on android 7 it is possible to decrease  display size and the scroll is working. On normal screen size it doesn't.

**Comment by zeevy** [comment] 2019-05-26 12:12
OK, i will fix the issue soon

**Comment by zeevy** [comment] 2019-06-09 16:14
this is fixed in free version of the application, you will get the update notification soon.
Please check and confirm the same

**Comment by zeevy** [comment] 2019-06-11 10:31
This issue is now fixed in both paid and free version

**Closed as completed** 2019-06-12 11:35 UTC
